# Generated by Django 2.2.9 on 2020-05-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Usuário', max_length=100)),
                ('email', models.CharField(help_text='Email', max_length=100)),
            ],
        ),
    ]
